name: Build Cloudflared Openwrt for MIPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cloudflared code from master
        uses: actions/checkout@v4
        with:
          repository: cloudflare/cloudflared
          ref: master
          
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Compile go dependency
        run: |
          .teamcity/install-cloudflare-go.sh

      - name: Compile code for MIPS
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: mips              # Big-endian build
          GOMIPS: softfloat
          LDFLAGS: "-s -w -extldflags=-static"
        run: |
          export BUILDTIME=$(date -u '+%Y-%m-%d-%H%M UTC')
          export PATH="/tmp/go/bin:$PATH"
          go build -a -installsuffix cgo -o $(pwd)/cloudflared-mips \
          -ldflags="-X 'main.Version=master' -X 'main.BuildTime=$BUILDTIME' -X 'main.BuildType=MIPS' $LDFLAGS" \
          $(pwd)/cmd/cloudflared

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-mips
          path: cloudflared-mips

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          
      - name: Create tarball release
        run: |
          mv artifacts/cloudflared-mips/cloudflared-mips ./cloudflared
          tar cvf cloudflared-mips-linux-master.tar.gz ./cloudflared
          
      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Cloudflared-Openwrt-master-MIPS
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: cloudflared-mips-linux-master.tar.gz
